from typing import List, Dict, Any
from datetime import datetime, timezone


def build_citations(
    retrieved_metadatas: List[Dict[str, Any]],
    retrieved_chunks: List[str],
) -> List[Dict[str, Any]]:
    """
    Builds a deduplicated citation list from retrieval metadata.

    Each citation references a unique source document.
    Multiple chunks from the same source are merged into one citation
    with a representative excerpt.

    Returns list of citation dicts ordered by first appearance.
    """
    seen_sources: Dict[str, Dict[str, Any]] = {}

    for idx, (meta, chunk) in enumerate(
        zip(retrieved_metadatas, retrieved_chunks)
    ):
        source = meta.get("source", f"source_{idx}")
        page = meta.get("page_number")
        doc_type = meta.get("type", "text")

        key = source

        if key not in seen_sources:
            seen_sources[key] = {
                "citation_number": len(seen_sources) + 1,
                "source": source,
                "type": doc_type,
                "pages": [],
                "excerpt": chunk[:200].strip(),
            }

        if page and page not in seen_sources[key]["pages"]:
            seen_sources[key]["pages"].append(page)

    return list(seen_sources.values())


def format_citations_block(citations: List[Dict[str, Any]]) -> str:
    """
    Renders citations as a markdown references section.
    """
    if not citations:
        return "_No source documents were retrieved for this report._"

    lines = []
    for c in citations:
        pages = c.get("pages", [])
        page_str = (
            f", pages {', '.join(str(p) for p in sorted(pages))}"
            if pages else ""
        )
        doc_type = c.get("type", "document")
        excerpt = c.get("excerpt", "")
        lines.append(
            f"**[{c['citation_number']}]** `{c['source']}`"
            f" ({doc_type}{page_str})\n"
            f"> {excerpt}..."
        )

    return "\n\n".join(lines)


def assemble_report(
    query: str,
    plan: List[dict],
    summary: str,
    citations: List[Dict[str, Any]],
    evaluation: Dict[str, Any],
    model: str,
    report_id: str,
) -> str:
    """
    Assembles the final markdown report from all pipeline outputs.

    Structure:
        - Header + metadata
        - Executive Summary (from summarizer)
        - Research Plan
        - Key Findings (extracted from summary)
        - Citations
        - Evaluation Metadata footer
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    plan_md = "\n".join(
        f"{item['step']}. **{item['task']}** — {item['reason']}"
        for item in plan
    )

    citations_md = format_citations_block(citations)

    confidence = evaluation.get("confidence_score", 0.0)
    passed = evaluation.get("passed", False)
    flags = evaluation.get("hallucination_flags", [])
    flags_md = (
        "\n".join(f"- ⚠️ {f}" for f in flags)
        if flags
        else "- ✅ No hallucination flags raised"
    )
    retries = evaluation.get("retry_count", 0)
    reasoning = evaluation.get("reasoning", "")

    report = f"""# Research Report

**Query:** {query}
**Generated:** {now}
**Model:** {model}
**Report ID:** `{report_id}`

---

## Executive Summary

{summary}

---

## Research Plan

{plan_md}

---

## Sources & Citations

{citations_md}

---

## Evaluation Metadata

| Metric | Value |
|---|---|
| Confidence Score | `{confidence:.4f}` |
| Evaluation Result | {'✅ Passed' if passed else '⚠️ Below Threshold'} |
| Retries | `{retries}` |
| Reasoning | {reasoning} |

**Quality Flags:**
{flags_md}

---

_Report generated by Autonomous Multi-Agent Research Assistant_
"""

    return report.strip()